
homeassistant:
  latitude: 52.662039
  longitude: 6.890839 
  elevation: 430
  unit_system: metric
  time_zone: Europe/Amsterdam
  name: Home

media_player:
  - platform: sonos
    hosts:
      - 10.0.0.20

frontend:

http:
  api_password: !env_var HOMEASSISTANT_PASSWORD

discovery:

history:

logbook:

sun:

# influxdb:
#   host: influxdb
#   database: homeassistant
#   username: homeassistant
#   password: !env_var INFLUXDB_PASSWORD

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433
  debug: false

sensor: !include sensors.yaml
light: !include lights.yaml
switch: !include switches.yaml
automation: !include automation.yaml
group: !include groups.yaml