version: '2'

services:
  homeassistant:
    image: homeassistant/rpi2-home-assistant:0.31.1
    restart: always
    ports:
      - "8123:8123"
    devices:
      - /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1LQ5JL-if00-port0:/dev/serial/by-id/usb-RFXCOM_RFXtrx433
    environment:
      HOMEASSISTANT_PASSWORD: "${HOME_PASSWORD}"
      INFLUXDB_PASSWORD: "${INFLUXDB_PASSWORD}"
    labels:
      - "traefik.backend=home"
      - "traefik.frontend.rule=Host:home.erwinsteffens.nl"
    volumes:
      - /usr/share/homeassistant:/config 
      - /etc/localtime:/etc/localtime:ro 
  influxdb:
    image: erwinsteffens/influxdb-armhf:1.0.2
    restart: always
    ports:
      - "8086:8086"
      - "8083:8083"
    volumes:
      - /usr/share/influxdb:/var/lib/influxdb
    labels:
      - "traefik.enable=false"
  grafana:
    image: fg2it/grafana-armhf:v3.1.1
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_DEFAULT_INSTANCE_NAME: home
      GF_PATHS_DATA: /data
      GF_SECURITY_ADMIN_USER: erwin
      GF_SECURITY_ADMIN_PASSWORD: "${HOME_PASSWORD}"
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - /usr/share/grafana:/data
    labels:
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:grafana.erwinsteffens.nl"
  traefik:
    image: hypriot/rpi-traefik:latest
    command: --web --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/share/traefik:/etc/traefik