
homeassistant:
  latitude: 52.662039
  longitude: 6.890839 
  elevation: 430
  unit_system: metric
  time_zone: Europe/Amsterdam
  name: Home

media_player:
  - platform: sonos
    hosts:
      - 10.0.0.20

frontend:

http:
  api_password: !env_var HOMEASSISTANT_PASSWORD

updater:

discovery:

history:

logbook:

sun:

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433
  debug: true

influxdb:
  host: influxdb
  database: home_assistant
  username: home_assistant
  password: test

sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
      - windSpeed
      - pressure
      - windDirection
  - platform: rfxtrx
    automatic_add: True

light:
  - platform: rfxtrx
    automatic_add: True

switch:
  - platform: rfxtrx
    automatic_add: True
